version: '3.1'

services:

  mongodb:
    image: mongo
    container_name: db-proyectofinal
    restart: always
    ports:
      - 2708:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: